parameters:
    customer.speaker.name: 'Heisenberg'

services:
#    customer.example:
#        class: CustomerBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    customer.speaker:
        class: CustomerBundle\Service\Speaker
        arguments: ['%customer.speaker.name%']
