customer_list:
    path:   /list
    defaults: { _controller: CustomerBundle:Default:list}

customer_create:
    path: /create
    defaults: { _controller: CustomerBundle:Default:create}

customer_id:
    resource: id.yml
    prefix: /{id}